version: '3'

services:
  mongo:
    image: mongo:4.2.21
    container_name: 20scoops_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - 20scoops_db:/data/db
  mongo-express:
    image: mongo-express
    container_name: 20scoops_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  web:
    build: .
    container_name: 20scoops_web
    command: yarn start:dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - mongo

volumes:
  20scoops_db:
