version: '3'

services:
  mongo:
    image: mongo:4.2.21
    container_name: 20scoops_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: 20scoops
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - 20scoops_db:/data/db
  web:
    build: .
    container_name: 20scoops_web
    command: yarn start:dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - mongo

volumes:
  20scoops_db:
